version: '3'
services:
  app:
    build: ./docker/go/
    tty: true
    volumes:
      - .:/go/src
    ports:
      - '10000:10000'
    environment:
      - MINIMUM_APP_DEV_DATABASE_NAME=article_dev
      - MINIMUM_APP_TEST_DATABASE_NAME=article_test
      - GO111MODULE=on
      - CGO_ENABLED=0
    depends_on:
      - db

  db:
    build: ./docker/db/
    volumes:
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    container_name: mysql